language: cpp
compiler:
  - clang
notifications:
  email: false
before_install:
  - sudo add-apt-repository ppa:staticfloat/julia-deps -y
  - sudo add-apt-repository ppa:staticfloat/julianightlies -y
  - sudo apt-get update -qq -y
  - sudo apt-get install libpcre3-dev julia -y
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=${HOME}/miniconda/bin:$PATH
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
  - conda install --yes numpy==1.8.2
  - conda install --yes matplotlib cython h5py setuptools mercurial sympy
  - hg clone http://bitbucket.org/yt_analysis/yt yt_test
  - cd yt_test && hg update tip && python setup.py install
  - cd ..
  - wget http://yt-project.org/data/enzo_tiny_cosmology.tar.gz
  - tar -zxvf enzo_tiny_cosmology.tar.gz
script:
  - julia -e 'Pkg.init(); run(`ln -s $(pwd()) $(Pkg.dir("YT"))`); Pkg.pin("YT"); Pkg.resolve()'
  - julia -e 'using YT; @assert isdefined(:YT); @assert typeof(YT) === Module'
  - export PYTHONPATH=test:$PYTHONPATH
  - python test/test_containers.py
  - python test/test_frbs.py
  - julia --code-coverage test/runtests.jl
after_success:
  - julia -e 'cd(Pkg.dir("YT")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'